//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Infor
    {
        public byte Id { get; set; }
        public string Name { get; set; }
        public string MoTa { get; set; }
        public string XuatPhat { get; set; }
        public Nullable<System.DateTime> NgayKH { get; set; }
        public string ThoiGian { get; set; }
        public Nullable<int> IdKhuVuc { get; set; }
        public string ImageTravel { get; set; }
        public string Gia { get; set; }
    
        public virtual KhuVuc KhuVuc { get; set; }
    }
}
